import 'package:barcode_widget/barcode_widget.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:qreeapp/models/qritem.dart';
import 'package:qreeapp/screens/about/about.dart';
import 'package:qreeapp/services/sqlite.dart';
// import 'package:qreeapp/shared/constants.dart';

import 'item_details.dart';

class Home extends StatefulWidget {
  const Home({super.key});

  @override
  State<Home> createState() => _HomeState();
}

class _HomeState extends State<Home> {
  final _db = SqliteService();
  final _menuList = <Map<String, dynamic>>[
    {
      'menu': 'About',
      'icon': Icons.info_rounded,
    },
  ];
  bool _isFabVisible = true;
  String _sort = 'byType';

  //
  // Scaffold.Menu
  //
  Widget _buildScaffoldMenu() {
    return PopupMenuButton(
      onSelected: (value) {
        switch (value) {
          case 'About':
            Navigator.of(context).push(
              MaterialPageRoute(
                builder: ((context) => const About()),
              ),
            );
            break;
          default:
            break;
        }
      },
      itemBuilder: (context) => _menuList
          .map(
            (e) => PopupMenuItem(
              value: e['menu'],
              child: Row(
                children: [
                  Icon(
                    e['icon'],
                    color: Theme.of(context).colorScheme.tertiary,
                  ),
                  const SizedBox(
                    width: 8.0,
                  ),
                  Text(e['menu']),
                ],
              ),
            ),
          )
          .toList(),
    );
  }

  //
  // ListTile
  //
  Widget _buildListTile(QrItem item) {
    return Card(
      // elevation: 4.0,
      child: ListTile(
        onTap: () {
          //
          // QR Code Dialog
          //
          showDialog(
            context: context,
            builder: (context) {
              return AlertDialog(
                contentPadding: EdgeInsets.zero,
                content: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Padding(
                      padding: const EdgeInsets.all(15.0),
                      child: Text(
                        item.title,
                        style: TextStyle(
                          fontSize: 20,
                          fontWeight: FontWeight.w300,
                          color: Theme.of(context).colorScheme.primary,
                        ),
                      ),
                    ),
                    Container(
                      color: Colors.white,
                      padding: const EdgeInsets.symmetric(
                          vertical: 8, horizontal: 24),
                      child: BarcodeWidget(
                        barcode: Barcode.qrCode(
                          errorCorrectLevel: BarcodeQRCorrectionLevel.high,
                        ),
                        data: item.info['data'],
                        width: 280,
                        height: 280,
                      ),
                    ),
                    Padding(
                      padding: const EdgeInsets.all(15.0),
                      child: Text(
                        item.text != null && item.text!.isNotEmpty
                            ? item.text!
                            : 'Generated by Qree',
                        style: TextStyle(
                          fontSize: 20,
                          fontWeight: FontWeight.w300,
                          color: Theme.of(context).colorScheme.secondary,
                        ),
                      ),
                      // padding: const EdgeInsets.all(16.0),
                      // child: OutlinedButton(
                      //   onPressed: () {},
                      //   style: OutlinedButton.styleFrom(
                      //       side: BorderSide(
                      //     color: Theme.of(context).colorScheme.error,
                      //   )),
                      //   child: Text(
                      //     dialogSubTitle,
                      //     style: TextStyle(
                      //       fontSize: 16,
                      //       fontWeight: FontWeight.bold,
                      //       color: Theme.of(context).colorScheme.error,
                      //     ),
                      //   ),
                      // ),
                    ),
                  ],
                ),
              );
            },
          );
        },
        leading: SizedBox(
            height: 26.0,
            width: 26.0,
            child: Center(
                child:
                    item.icon(color: Theme.of(context).colorScheme.tertiary))),
        title: Text(item.title),
        //
        // Item Details
        //
        contentPadding: const EdgeInsets.only(
            left: 14.0, right: 8.0, top: 2.0, bottom: 2.0),
        trailing: IconButton(
          icon: Icon(
            Icons.edit_outlined,
            color: Theme.of(context).colorScheme.primary,
          ),
          visualDensity: VisualDensity.compact,
          onPressed: () {
            Navigator.of(context)
                .push(MaterialPageRoute(
                    builder: (context) => ItemDetails(item: item)))
                .then(
              (value) {
                if (value == true) {
                  setState(() {});
                }
              },
            );
          },
        ),
      ),
    );
  }

  //
  // Floating Action Button
  //
  FloatingActionButton? _buildFab() {
    return _isFabVisible
        ? FloatingActionButton(
            // elevation: 8,
            backgroundColor: Theme.of(context)
                .colorScheme
                .primaryContainer
                .withOpacity(0.75),
            onPressed: () {
              showDialog<QrType>(
                context: context,
                builder: (context) {
                  return SimpleDialog(
                    title: const Text('QR Code Type'),
                    children: QrType.values
                        .map((e) => SimpleDialogOption(
                            child: Padding(
                              padding: const EdgeInsets.all(4.0),
                              child: Text(
                                e.getName(),
                                style: TextStyle(
                                  color: Theme.of(context).colorScheme.tertiary,
                                  fontSize: 16.0,
                                ),
                              ),
                            ),
                            onPressed: () {
                              Navigator.of(context).pop(e);
                            }))
                        .toList(),
                  );
                },
              ).then((value) {
                if (value is QrType) {
                  final item = QrItem.defaultByType(value);
                  // _navigateToItemDetailPage(item);
                  Navigator.of(context)
                      .push(MaterialPageRoute(
                          builder: (context) => ItemDetails(item: item)))
                      .then(
                    (value) {
                      if (value == true) {
                        setState(() {});
                      }
                    },
                  );
                }
              });
            },
            child: const Icon(Icons.add_rounded),
          )
        : null;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        // title: const Text('QRee'),
        title: TextButton.icon(
          onPressed: () {
            if (_sort == 'byTitle') {
              _sort = 'byType';
            } else {
              _sort = 'byTitle';
            }
            setState(() {});
          },
          label: Text('QRee',
              style: TextStyle(
                fontSize: 20,
                fontWeight: FontWeight.w300,
                color: Theme.of(context).colorScheme.onSurface,
              )),
          icon: SizedBox(
            width: 32.0,
            height: 32.0,
            child: Image.asset('assets/images/scan-128.png'),
          ),
        ),
        // title: Row(
        //   children: [
        //     SizedBox(
        //       width: 32.0,
        //       height: 32.0,
        //       child: Image.asset('assets/images/scan-128.png'),
        //     ),
        //     const SizedBox(width: 12.0),
        //     const Text('QRee'),
        //   ],
        // ),
        actions: <Widget>[
          _buildScaffoldMenu(),
        ],
      ),
      body: NotificationListener<UserScrollNotification>(
        onNotification: (notification) {
          if (notification.direction == ScrollDirection.forward) {
            if (!_isFabVisible) setState(() => _isFabVisible = true);
          } else if (notification.direction == ScrollDirection.reverse) {
            if (_isFabVisible) setState(() => _isFabVisible = false);
          }
          return false;
        },
        child: Padding(
          padding: const EdgeInsets.all(8.0),
          child: FutureBuilder<List<QrItem>>(
            future: _db.getQrItems(),
            builder: (context, snapshot) {
              if (snapshot.hasData) {
                final qrItems = snapshot.data!;
                qrItems.sort((a, b) => _sort == 'byTitle'
                    ? a.title.compareTo(b.title)
                    : a.type.name.compareTo(b.type.name));
                return ListView.builder(
                    itemCount: qrItems.length,
                    itemBuilder: (context, index) {
                      return _buildListTile(qrItems[index]);
                    });
              } else {
                return Center(
                  child: SizedBox(
                    width: 200.0,
                    height: 200.0,
                    child: Image.asset('assets/images/scan-128.png'),
                  ),
                );
              }
            },
          ),
        ),
      ),
      floatingActionButton: _buildFab(),
      floatingActionButtonLocation: FloatingActionButtonLocation.centerFloat,
    );
  }
}
