import 'package:flutter/material.dart';

// app info
const appName = 'QRee';
const appId = 'com.innomatic.qreeapp';
const appVersion = '1.2.0+6';
const urlPlayStore = 'https://play.google.com/store/apps/details?id=$appId';
const urlAppStore = null;
const urlHomePage = 'https://innomatic.ca';
const emailDeveloper = 'nuntium.ubique@gmail.com';

// urls
const urlPrivacyPolicy = 'https://innomatica.github.io/qree/privacy/';
const urlDisclaimer = 'https://innomatica.github.io/qree/disclaimer/';
const urlAppIconSource = 'https://www.flaticon.com/free-icon/scan_6270202';
const urlStoreImageSource = 'https://unsplash.com/@dafidvor';

// colors
const seedColorLight = Color.fromRGBO(118, 124, 27, 1);
const fabBgndColorLight = Color.fromARGB(100, 60, 102, 89);

const seedColorDark = Color.fromRGBO(224, 238, 51, 1.0);
const fabBgndColorDark = Color.fromARGB(100, 163, 208, 192);

// texts
const dialogSubTitle = 'Generated by QRee';
